default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["UNICASH_NOTIFICATION_DATABASE_URL"] %>

development:
  <<: *default
  database: unicash_notification_development

test:
  <<: *default
  database: unicash_notification_test

production:
  <<: *default
  database: unicash_notification_production
